project:
  name: "Rush Java"
  intra_url: "rush-java"
  begin:  "2017-04-13 11:00:00"
  end:    "2017-04-14 23:42:00"
  git_url: git@git.acu.epita.fr:rush-java-2019/login_x-rush-java.git

managers:
    - login: boutin_a
      fullname: Maxime Boutin
    - login: deutsc_t
      fullname: Thibault Deutsch
    - login: fresne_m
      fullname: Marc Fresne
    - login: liotie_t
      fullname: Thibault Liotier
    - login: lugand_j
      fullname: Jérémy Lugand
    - login: orfila_c
      fullname: Cyprien Orfila
    - login: vidal_m
      fullname: Mathieu Vidal
    - login: youino_f
      fullname: Florent Youinou

newsgroup:
    name: assistants.projets
    tag: RJV

languages:
    - id: java
      targets: [javac]

targets:
    - id: javac
      type: compiler
      name: javac

submissions:
    - name: Submission
      begin:  "2017-04-14 21:00:00"
      end:    "2017-04-14 23:42:00"
      tag:    submission

defenses:
    - name: Defense
      begin: "2017-04-20 20:00:00"
      filepath: defenses/defense.xml

documents:
    - name: subject.pdf
      filepath: subjects/subject.pdf
      type: subject
      begin: "2017-04-13 11:00:00"
#    - name: creeps.pdf
#      type: file
#      date: 2016-04-15 21:00:00
#    - name: creeps-login_l.tar.bz2
#      type: file
#      date: 2016-04-15 21:00:00
