project:
  name: &project_name "Rush Java"
  intra_url: "rush-java"
  begin: &project_begin "2018-04-13 11:00:00"
  end:   &project_end "2018-04-14 23:42:00"
  git_url: git@git.acu.epita.fr:rush-java-2020/login_x-rush-java.git
  tag_prefix: &project_tag deploy-rushjava-2020

managers:
    - login: bennac_k
      fullname: Kais Ben Naceur
    - login: charpe_f
      fullname: Eloi Charpentier

newsgroup:
    name: assistants.projets
    tag: RJV

languages:
    - id: java
      targets: [javac]

targets:
    - id: javac
      type: compiler
      name: javac

documents:
    - name: subject.pdf
      path: subjects/subject.pdf
    - name: slides.pdf
      path: slides/slides.pdf
    - name: creeps.tar.bz2
      path: files/creeps.tar.bz2

steps:
    - name: *project_name
      begin: *project_begin
      end: *project_end
      tag_prefix: *project_tag
      submissions:
          - name: Submission
            begin:  "2018-04-14 21:00:00"
            end:    "2018-04-14 23:42:00"
            tag:    submission
      defenses:
          - name: Defense
            begin: "2018-04-20 20:00:00"
            path: defenses/defense.xml
