---
- name: create /opt/node-exporter
  file:
    path: /opt/node-exporter
    state: directory
    mode: 0755

- name: copy node-exporter
  copy:
    src: node_exporter
    dest: /opt/node-exporter/node_exporter
    mode: 0755

- name: copy node-exporter.service
  copy:
    src: node-exporter.service
    dest: /etc/systemd/system/node-exporter.service

- name: start node-exporter.service
  raw: systemctl daemon-reload; systemctl stop node-exporter; killall node-exporter; systemctl restart node-exporter
