---
- name: Poweroff nodes
  user: root
  hosts: nodes
  vars_prompt:
      - name: 'check_poweroff'
        prompt: 'Poweroff everything? [y/n]'
        default: 'n'
        private: no
  vars:
    ansible_python_interpreter: "/usr/bin/python2.7"
  tasks:
  - name: Poweroff
    raw: poweroff
    when: check_poweroff == 'y'
